# Generated by Django 2.0.1 on 2018-01-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_usuari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuari',
            name='correos',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
