# Generated by Django 2.0.1 on 2018-01-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180114_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuari',
            new_name='Usuarios',
        ),
    ]
