# Generated by Django 2.0.1 on 2018-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180114_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correos',
            field=models.CharField(max_length=40),
        ),
    ]
