# Generated by Django 2.0.1 on 2018-01-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180114_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuari',
        ),
    ]
