# Generated by Django 2.0.1 on 2018-01-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180114_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuari',
            name='correos',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
